# Numpy Playground

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
heights = [60, 70, 80, 90]
heights_arr = np.array(heights)

In [4]:
type(heights_arr)

numpy.ndarray

In [5]:
heights_arr * 2.54

array([152.4, 177.8, 203.2, 228.6])

---

## ایجاد یک آرایه ساده (ndarray)

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2.5, 3, 4, 5])

In [7]:
print(arr1)

[1 2 3 4 5]


## ایجاد آرایه های چندبعدی

In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                   [[9, 10, 11, 12], [13, 14, 15, 16]],
                   [[10, 20, 30, 40], [50, 60, 70, 80]]])
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[10 20 30 40]
  [50 60 70 80]]]


## مشاهده ویژگی های آرایه

In [10]:
print(arr1.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(5,)
(2, 3)
(3, 2, 4)


In [11]:
print(arr1.dtype)
print(arr2.dtype)

int64
float64


In [12]:
print(arr_2d.size)
print(arr_3d.size)

6
24


## تغییر نوع و ابعاد آرایه

In [13]:
# change data type
arr2 = arr2.astype('float16')
# arr2 = arr2.astype(np.float16)
arr2.dtype

dtype('float16')

In [14]:
arr_2d_2 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

In [15]:
arr_2d_2.size

12

In [16]:
arr_2d_2.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
arr_2d_2.reshape(1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [18]:
arr_2d_2.reshape(1, 12).shape

(1, 12)

In [19]:
arr_2d_2.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [20]:
arr_2d_2.reshape(12, 1).shape

(12, 1)

In [21]:
arr_2d_2.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## توابع ایجاد آرایه

In [22]:
print(np.zeros(5))
print('-'*30)
print(np.zeros([3, 4]))
print('-'*30)
print(np.ones(5))
print('-'*30)
print(np.ones([3, 4]))

[0. 0. 0. 0. 0.]
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[1. 1. 1. 1. 1.]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
print(np.random.random(5))
print('-'*30)
print(np.random.random([2, 3]))
print('-'*30)
print(np.random.randint(0, 6, [4, 4]))  # (low, high, size)

[0.29793249 0.35048056 0.27203231 0.47111624 0.21289428]
------------------------------
[[0.62604965 0.70503488 0.7373323 ]
 [0.53177225 0.98341147 0.24301829]]
------------------------------
[[5 4 4 3]
 [1 2 2 1]
 [2 5 4 5]
 [2 3 3 1]]


In [24]:
print(np.arange(1, 10))  # (start, stop)
print('-'*30)           
print(np.arange(1, 20, 2))  # (start, stop, step)
print('-'*30)
print(np.arange(0, 1, 0.1))
print('-'*30)
print(np.linspace(0, 1, 9))  # (start, stop, num)

[1 2 3 4 5 6 7 8 9]
------------------------------
[ 1  3  5  7  9 11 13 15 17 19]
------------------------------
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
------------------------------
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [25]:
print(np.full([3, 4], 5))  # (shape, value)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
mat_ones = np.ones([3, 4])
mat_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
mat1 = mat_ones * np.array([1, 2, 3, 4])
mat1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [28]:
np.array([1, 2, 3]).reshape(-1, 1)

array([[1],
       [2],
       [3]])

In [29]:
mat2 = mat_ones * np.array([1, 2, 3]).reshape(-1, 1)
mat2

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

## محورها (Axis)

In [30]:
print(np.sum(mat1))
print(np.sum(mat1, axis=0))
print(np.sum(mat1, axis=1))

30.0
[ 3.  6.  9. 12.]
[10. 10. 10.]


In [31]:
print(np.mean(mat1))
print(np.mean(mat1, axis=0))
print(np.mean(mat1, axis=1))

2.5
[1. 2. 3. 4.]
[2.5 2.5 2.5]


## عملیات برداری و ماتریسی

In [32]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 2])

In [33]:
print(vec1 * vec2)
print(np.multiply(vec1, vec2))

[2 4 6]
[2 4 6]


In [34]:
# Dot product
print(vec1 @ vec2)
print(np.dot(vec1, vec2))

12
12


In [35]:
# Cross product
print(np.cross(vec1, vec2))

[-2  4 -2]


In [36]:
mat_1 = np.full([3, 4], 2)
mat_2 = np.full([3, 4], 5)

In [37]:
print(mat_1 * mat_2)
print('-'*30)
print(np.multiply(mat_1, mat_2))

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
------------------------------
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [38]:
print(mat1 @ np.transpose(mat_2))
print('-'*30)
print(np.matmul(mat1, np.transpose(mat_2)))

[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]
------------------------------
[[50. 50. 50.]
 [50. 50. 50.]
 [50. 50. 50.]]


## Conditional Indexing / Filtering

In [41]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# Greater than 5
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [43]:
# Greater than 5
arr[arr > 5]

array([6, 7, 8, 9])

In [44]:
# Greater than 2 AND Less than 6  (2<x<6)
arr[(arr>2) & (arr<6)]

array([3, 4, 5])

In [45]:
# Less than 2 OR Greater than 6  (x<2 or x>6)
arr[(arr<2) | (arr>6)]

array([1, 7, 8, 9])

In [48]:
# number of items greater than 5
print(np.sum(arr > 5))

4


In [49]:
# items that are greater than 5 (where)
print(np.where(arr > 5))

(array([5, 6, 7, 8]),)


## Roots of a polynomial function

In [50]:
# x^2 - 5X + 6 = (x-2)(x-3) => roots: 2, 3
np.roots([1, -5, 6])

array([3., 2.])

In [53]:
# 3x^3 - 5x + 5
np.roots([3, 0, 5, 5]).round(2)

array([ 0.37+1.44j,  0.37-1.44j, -0.75+0.j  ])